version: '3'
services:
  backend:
    container_name: dropwizard-YixinZ
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "10020:8080"
      - "10021:8081"


  frontend:
    container_name: react-YixinZ
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - '12300:3000'
    depends_on:
          - backend
