version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "10020:8080"
      - "10021:8081"
    networks:
      - project_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - '12300:3000'
    depends_on:
          - backend
    networks:
          - project_network
networks:
  project_network:
     driver: bridge